"""Measures an episode's captioned claims over 20 seeds and writes
studio/episodes/<episode>/measurements.md:

    python3 studio/measure.py EPISODE

Each episode's `claims.py` defines `measure(tmp) -> (lines, verdicts)`: the
report's tables, and one (claim, holds, why) per captioned claim. This
module holds what they share: running the CLI, summaries, typical seeds.
"""

import csv
import json
import pathlib
import statistics
import subprocess
import sys
import tempfile

STUDIO = pathlib.Path(__file__).resolve().parent
REPO = STUDIO.parent
CLI = REPO / "target" / "release" / "sugarscape"
SEEDS = range(1, 21)

sys.path.insert(0, str(STUDIO))

import dump  # noqa: E402
import episode  # noqa: E402


def summary(values):
    return {"median": statistics.median(values), "lo": min(values), "hi": max(values)}


def median(rows, key):
    """The median over seeds of one measure (`rows` maps seed → measures)."""
    return statistics.median(r[key] for r in rows.values())


def typical_seed(rows, keys):
    """The seed whose values are, in total, closest to the medians (each
    measure scaled by its range across seeds)."""
    stats = {k: summary([r[k] for r in rows.values()]) for k in keys}

    def distance(seed):
        return sum(
            abs(rows[seed][k] - stats[k]["median"]) / ((stats[k]["hi"] - stats[k]["lo"]) or 1)
            for k in keys
        )

    return min(sorted(rows), key=distance)


def run(preset, seed, ticks, tmp):
    """The series and final agents (as CSV rows) of a preset run."""
    series, agents = tmp / f"{preset}-{seed}.csv", tmp / f"{preset}-{seed}-agents.csv"
    subprocess.run(
        [CLI, "run", "--preset", preset, "--seed", str(seed), "--ticks", str(ticks),
         "--series-csv", series, "--agents-csv", agents],
        check=True,
    )
    with open(series) as f:
        s = list(csv.DictReader(f))
    with open(agents) as f:
        a = list(csv.DictReader(f))
    return s, a


def shot(spec, tmp, name):
    """Runs a shot (a dict, as in a shot file) and loads its frame dump."""
    src, out = tmp / f"{name}.json", tmp / f"{name}.frames.json"
    src.write_text(json.dumps(spec))
    subprocess.run([CLI, "shot", src, "--out", out], check=True)
    return dump.load(out)


def table(rows, keys):
    lines = ["| measure | median | min | max |", "|---|---|---|---|"]
    for k in keys:
        v = summary([r[k] for r in rows.values()])
        lines.append(f"| {k} | {v['median']:.3f} | {v['lo']:.3f} | {v['hi']:.3f} |")
    return lines


def main(name):
    subprocess.run(["cargo", "build", "--release", "-q", "-p", "sugarscape-cli"], check=True, cwd=REPO)
    claims = episode.load_module(name, "claims")
    with tempfile.TemporaryDirectory() as t:
        lines, verdicts = claims.measure(pathlib.Path(t))
    lines = [f"# {name}: measurements (seeds 1–20)", "", f"Generated by `python3 studio/measure.py {name}`.", "", *lines]
    lines += ["", "## Captions", ""]
    for claim, holds, why in verdicts:
        lines.append(f"- {'holds' if holds else 'DOES NOT HOLD'}: {claim} — {why}.")
    lines.append("")
    path = episode.episode_dir(name) / "measurements.md"
    path.write_text("\n".join(lines))
    print(path.read_text())


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "sugarscape")
