"""Measures the pilot's captioned claims over 20 seeds and writes
studio/episodes/sugarscape/measurements.md. Run: python3 studio/measure.py"""

import csv
import json
import pathlib
import statistics
import subprocess
import tempfile

STUDIO = pathlib.Path(__file__).resolve().parent
REPO = STUDIO.parent
CLI = REPO / "target" / "release" / "sugarscape"
SEEDS = range(1, 21)
HILL = 3  # a site of capacity ≥ 3 is on a hill


def summary(values):
    return {"median": statistics.median(values), "lo": min(values), "hi": max(values)}


def typical_seed(rows, keys):
    """The seed whose values are, in total, closest to the medians (each
    measure scaled by its range across seeds)."""
    stats = {k: summary([r[k] for r in rows.values()]) for k in keys}

    def distance(seed):
        return sum(
            abs(rows[seed][k] - stats[k]["median"]) / ((stats[k]["hi"] - stats[k]["lo"]) or 1)
            for k in keys
        )

    return min(sorted(rows), key=distance)


def verdicts(ii2, ii5, hill_share, rose):
    """Each captioned claim, whether the 20 seeds support it, and why."""
    med = lambda rows, k: statistics.median(r[k] for r in rows.values())  # noqa: E731
    pop25, hills = med(ii2, "pop25"), med(ii2, "on_hills")
    g0, g500, skew = med(ii5, "gini0"), med(ii5, "gini500"), med(ii5, "mean_over_median")
    return [
        ("many poof early (beat 7)", pop25 < 0.8 * 400, f"median population at tick 25 is {pop25:g} of 400"),
        ("survivors crowd the hills (beats 7–8)", hills > 2 * hill_share,
         f"{hills:.0%} of survivors on hill sites, which are {hill_share:.0%} of the board"),
        ("sight up, hunger down (beat 8 dials)", rose >= 18, f"in {rose} of 20 seeds"),
        ("some are rich (beat 9)", g500 > g0 + 0.1 and skew > 1.2,
         f"Gini {g0:.2f} → {g500:.2f}; mean holding {skew:.2f} × the median"),
    ]


def _run(preset, seed, ticks, tmp):
    series, agents = tmp / f"{preset}-{seed}.csv", tmp / f"{preset}-{seed}-agents.csv"
    subprocess.run(
        [CLI, "run", "--preset", preset, "--seed", str(seed), "--ticks", str(ticks),
         "--series-csv", series, "--agents-csv", agents],
        check=True,
    )
    with open(series) as f:
        s = list(csv.DictReader(f))
    with open(agents) as f:
        a = list(csv.DictReader(f))
    return s, a


def _capacity(tmp):
    shot = tmp / "landscape.json"
    shot.write_text(json.dumps({"preset": "ii-2-unit", "ticks": 0, "set": {"population": 0}}))
    out = subprocess.run([CLI, "shot", shot], capture_output=True, text=True, check=True)
    return json.loads(out.stdout)["capacity"]


def _table(rows, keys):
    lines = ["| measure | median | min | max |", "|---|---|---|---|"]
    for k in keys:
        v = summary([r[k] for r in rows.values()])
        lines.append(f"| {k} | {v['median']:.3f} | {v['lo']:.3f} | {v['hi']:.3f} |")
    return lines


def main():
    subprocess.run(["cargo", "build", "--release", "-q", "-p", "sugarscape-cli"], check=True, cwd=REPO)
    ii2, ii5 = {}, {}
    with tempfile.TemporaryDirectory() as t:
        tmp = pathlib.Path(t)
        cap = _capacity(tmp)
        hill_share = sum(c >= HILL for c in cap) / len(cap)
        for seed in SEEDS:
            s, a = _run("ii-2-unit", seed, 300, tmp)
            on_hills = sum(cap[int(r["y"]) * 50 + int(r["x"])] >= HILL for r in a) / max(len(a), 1)
            ii2[seed] = {
                "pop0": float(s[0]["population"]),
                "pop25": float(s[25]["population"]),
                "pop300": float(s[300]["population"]),
                "on_hills": on_hills,
                "vision0": float(s[0]["mean_vision"]),
                "vision300": float(s[300]["mean_vision"]),
                "metab0": float(s[0]["mean_metabolism"]),
                "metab300": float(s[300]["mean_metabolism"]),
            }
            s, a = _run("ii-5-wealth", seed, 500, tmp)
            sugar = sorted(float(r["sugar"]) for r in a)
            top = sugar[int(len(sugar) * 0.9):]
            ii5[seed] = {
                "gini0": float(s[0]["gini"]),
                "gini500": float(s[500]["gini"]),
                "mean_over_median": statistics.mean(sugar) / statistics.median(sugar),
                "top10_share": sum(top) / sum(sugar),
            }
    rose = sum(r["vision300"] > r["vision0"] and r["metab300"] < r["metab0"] for r in ii2.values())
    lines = ["# Pilot measurements (seeds 1–20)", "", "Generated by `python3 studio/measure.py`.", ""]
    lines += ["## ii-2-unit, 300 ticks (beats 7–8)", ""]
    lines += _table(ii2, ["pop0", "pop25", "pop300", "on_hills", "vision0", "vision300", "metab0", "metab300"])
    lines += [
        "",
        f"Share of all sites with capacity ≥ {HILL}: {hill_share:.3f}.",
        f"Seeds where mean vision rose and mean metabolism fell: {rose} of 20.",
        f"Typical seed: {typical_seed(ii2, ['pop300', 'on_hills', 'vision300', 'metab300'])}.",
        "",
        "## ii-5-wealth, 500 ticks (beat 9)",
        "",
    ]
    lines += _table(ii5, ["gini0", "gini500", "mean_over_median", "top10_share"])
    lines += ["", f"Typical seed: {typical_seed(ii5, ['gini500', 'top10_share'])}.", ""]
    lines += ["## Captions", ""]
    for claim, holds, why in verdicts(ii2, ii5, hill_share, rose):
        lines.append(f"- {'holds' if holds else 'DOES NOT HOLD'}: {claim} — {why}.")
    lines.append("")
    path = STUDIO / "episodes" / "sugarscape" / "measurements.md"
    path.write_text("\n".join(lines))
    print(path.read_text())


if __name__ == "__main__":
    main()
