"""Measures an episode's captioned claims over 20 seeds and writes
studio/episodes/<episode>/measurements.md:

    python3 studio/measure.py EPISODE

Each episode's `claims.py` defines `measure(tmp) -> (lines, verdicts)`: the
report's tables, and one (claim, holds, why) per captioned claim. This
module holds what they share: running the CLI, summaries, typical seeds.
"""

import csv
import json
import pathlib
import statistics
import subprocess
import sys
import tempfile

STUDIO = pathlib.Path(__file__).resolve().parent
REPO = STUDIO.parent
CLI = REPO / "target" / "release" / "sugarscape"
SEEDS = range(1, 21)

sys.path.insert(0, str(STUDIO))

import dump  # noqa: E402
import episode  # noqa: E402


def summary(values):
    return {"median": statistics.median(values), "lo": min(values), "hi": max(values)}


def median(rows, key):
    """The median over seeds of one measure (`rows` maps seed → measures)."""
    return statistics.median(r[key] for r in rows.values())


def typical_seed(rows, keys):
    """The seed whose values are, in total, closest to the medians (each
    measure scaled by its range across seeds)."""
    stats = {k: summary([r[k] for r in rows.values()]) for k in keys}

    def distance(seed):
        return sum(
            abs(rows[seed][k] - stats[k]["median"]) / ((stats[k]["hi"] - stats[k]["lo"]) or 1)
            for k in keys
        )

    return min(sorted(rows), key=distance)


def with_changes(config, changes):
    """`config` (a dict) with each dotted path in `changes` set, as a shot's
    `set` does."""
    config = json.loads(json.dumps(config))
    for path, value in changes.items():
        *parents, last = path.split(".")
        node = config
        for key in parents:
            node = node[int(key)] if isinstance(node, list) else node[key]
        if isinstance(node, list):
            node[int(last)] = value
        else:
            node[last] = value
    return config


def preset_config(preset, tmp):
    """A preset's config as a dict, as the CLI loads it."""
    out = tmp / f"{preset}.config.json"
    if not out.exists():
        subprocess.run([CLI, "run", "--preset", preset, "--ticks", "0", "--config-out", out],
                       check=True, stdout=subprocess.DEVNULL)
    return json.loads(out.read_text())


def run(preset, seed, ticks, tmp, changes=None):
    """The series and final agents (as CSV rows) of a preset run, with any
    `changes` to its config (dotted paths, as a shot's `set`)."""
    name = preset + ("-" + "-".join(f"{k}={v}" for k, v in sorted(changes.items())) if changes else "")
    series, agents = tmp / f"{name}-{seed}.csv", tmp / f"{name}-{seed}-agents.csv"
    source = ["--preset", preset]
    if changes:
        config = tmp / f"{name}.json"
        config.write_text(json.dumps(with_changes(preset_config(preset, tmp), changes)))
        source = ["--config", config]
    subprocess.run(
        [CLI, "run", *source, "--seed", str(seed), "--ticks", str(ticks),
         "--series-csv", series, "--agents-csv", agents],
        check=True, stdout=subprocess.DEVNULL,
    )
    with open(series) as f:
        s = list(csv.DictReader(f))
    with open(agents) as f:
        a = list(csv.DictReader(f))
    return s, a


def shot(spec, tmp, name):
    """Runs a shot (a dict, as in a shot file) and loads its frame dump."""
    src, out = tmp / f"{name}.json", tmp / f"{name}.frames.json"
    src.write_text(json.dumps(spec))
    subprocess.run([CLI, "shot", src, "--out", out], check=True)
    return dump.load(out)


def table(rows, keys):
    lines = ["| measure | median | min | max |", "|---|---|---|---|"]
    for k in keys:
        v = summary([r[k] for r in rows.values()])
        lines.append(f"| {k} | {v['median']:.3f} | {v['lo']:.3f} | {v['hi']:.3f} |")
    return lines


def main(name):
    subprocess.run(["cargo", "build", "--release", "-q", "-p", "sugarscape-cli"], check=True, cwd=REPO)
    claims = episode.load_module(name, "claims")
    with tempfile.TemporaryDirectory() as t:
        lines, verdicts, *rest = claims.measure(pathlib.Path(t))
    if rest:
        # Values for on-screen panels (e.g. medians over the seeds).
        path = episode.episode_dir(name) / "measurements.json"
        path.write_text(json.dumps(rest[0], indent=2, sort_keys=True) + "\n")
    lines = [f"# {name}: measurements (seeds 1–20)", "", f"Generated by `python3 studio/measure.py {name}`.", "", *lines]
    lines += ["", "## Captions", ""]
    for claim, holds, why in verdicts:
        lines.append(f"- {'holds' if holds else 'DOES NOT HOLD'}: {claim} — {why}.")
    lines.append("")
    path = episode.episode_dir(name) / "measurements.md"
    path.write_text("\n".join(lines))
    print(path.read_text())


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "sugarscape")
