use sugarscape_core::{retirement::*,model::Model};
use std::{fs::{File,create_dir_all},io::{Write,BufWriter},time::Instant};
fn val(x:Option<u64>)->String{x.map(|v|v.to_string()).unwrap_or_default()}
fn main(){let args:Vec<String>=std::env::args().collect();let batch=args.get(1).map(String::as_str).unwrap_or("policy");let limit:u64=args.get(2).and_then(|s|s.parse().ok()).unwrap_or(50);let start_seed:u64=args.get(4).and_then(|s|s.parse().ok()).unwrap_or(1001);let out=args.get(3).map(String::as_str).unwrap_or("..");create_dir_all(out).unwrap();let mut cases:Vec<(String,RetirementConfig,&str,u64)>=vec![];
let base=RetirementConfig::default();
if batch=="policy"{for (label,th,sd) in [("ae",0.5,0.0),("gss",0.75,0.14433756729740646)]{for r in [0.01,0.02,0.04,0.05]{for warm in ["auto","fixed","sustained"]{let mut c=base.clone();c.rational=r;c.threshold=th;c.spread=sd;c.mandatory=70;c.policy.enabled=warm=="auto";cases.push((format!("policy_{label}_{r}_{warm}"),c,warm,1100));}}}}
if batch=="trajectories"{for r in [0.15,0.20,0.05]{let mut c=base.clone();c.rational=r;cases.push((format!("trajectory_{r}"),c,"none",500));}}
if batch=="groups" || batch=="groups-source"{for k in [0.05,0.08,0.10,0.12,0.15,0.20]{let mut c=base.clone();c.rational=if batch=="groups-source"{0.10}else{0.05};c.groups.enabled=true;c.groups.coupling=k;cases.push((format!("{batch}_{k}"),c,"none",600));}}
if batch=="sensitivities"{for e in 6..=10{let mut c=base.clone();c.rational=0.05;c.extent=e;cases.push((format!("extent_{e}"),c,"none",600));}for hw in [0.,0.05,0.1,0.2,0.3,0.4,0.5]{let mut c=base.clone();c.rational=0.05;c.spread=hw/3f64.sqrt();cases.push((format!("spread_{hw}"),c,"none",600));}}
if batch=="spread-source"{for hw in [0.,0.05,0.1,0.2,0.3,0.4,0.5]{let mut c=base.clone();c.spread=hw/3f64.sqrt();cases.push((format!("spread-source_{hw}"),c,"none",600));}}
if batch=="cohort-source"{for pc in [200,300]{let mut c=base.clone();c.per_cohort=pc;cases.push((format!("cohort-source_{pc}"),c,"none",600));}}
if batch=="critical"{for renewal in [Renewal::Slot,Renewal::Replace]{for r in [0.,0.02,0.05,0.10]{let mut c=base.clone();c.renewal=renewal;c.rational=r;cases.push((format!("critical_{renewal:?}_{r}"),c,"none",2000));}}}
if batch=="counts"{for renewal in [Renewal::Slot,Renewal::Replace]{for counts in [Counts::Eligible,Counts::All]{let mut c=base.clone();c.renewal=renewal;c.counts=counts;cases.push((format!("counts_{renewal:?}_{counts:?}"),c,"none",600));}}}
let mut sum=BufWriter::new(File::create(format!("{out}/{batch}-seeds.csv")).unwrap());writeln!(sum,"case,seed,horizon,switch,previous_tick_mode_at_switch,first95,first99,first100,dips95,dips99,dips100,sustained65,sustained62_post,proxy_new,group_a,group_b,final_share,final_mode,imitator_events").unwrap();let start=Instant::now();
for (name,c,warm,horizon) in cases{std::fs::write(format!("{out}/{name}-config.json"),serde_json::to_string_pretty(&c).unwrap()).unwrap();for seed in start_seed..start_seed+limit{let mut w=RetirementWorld::new(c.clone(),seed).unwrap();if c.groups.enabled {let mut membership=BufWriter::new(File::create(format!("{out}/{name}-{seed}-membership.csv")).unwrap());writeln!(membership,"group,living,rational,random").unwrap();for g in 0..2 {let a:Vec<_>=w.agents().iter().filter(|a|a.group==g).collect();writeln!(membership,"{g},{},{},{}",a.len(),a.iter().filter(|a|a.kind==Kind::Rational).count(),a.iter().filter(|a|a.kind==Kind::Random).count()).unwrap();}}let mut trace=if batch!="cohort-source"&&seed<start_seed+2{Some(BufWriter::new(File::create(format!("{out}/{name}-{seed}-trace.csv")).unwrap()))}else{None};if let Some(f)=trace.as_mut(){writeln!(f,"tick,retired,modal_age,mean_age,eligibility,new_events,imitator_events,age_events,rolling_age_retirements_exposures").unwrap();}let mut first=[None;3];let mut dips=[0u64;3];let mut switch=None;let mut previous_tick_mode_at_switch=f64::NAN;let mut sustained65=None;let mut post62=None;let(mut run65,mut run62)=(0,0);let mut imit=0u64;
for _ in 0..horizon{let prev:Vec<_>=w.agents().iter().map(|a|(a.born,a.retired)).collect();let oldelig=w.eligibility();let oldmode=w.stats.history().last().unwrap().modal_age;w.step();let t=w.tick();let s=w.stats.history().last().unwrap();let mut ages=[0u32;101];let mut ni=0u64;for(i,a)in w.agents().iter().enumerate(){if prev[i].0==a.born&&!prev[i].1&&a.retired{if let Some(age)=a.retired_at{ages[age as usize]+=1;}if a.kind==Kind::Imitator{ni+=1;}}}imit+=ni;
for(j,th)in [0.95,0.99,1.0].iter().enumerate(){if s.retired>=*th{if first[j].is_none(){first[j]=Some(t);}}else if first[j].is_some(){dips[j]+=1;}}
if s.modal_age==65.0{run65+=1;}else{run65=0;}if run65>=10&&sustained65.is_none(){sustained65=Some(t);}
if oldelig!=w.eligibility(){switch=Some(t);previous_tick_mode_at_switch=oldmode;run62=0;}if switch.is_some()&&s.modal_age==62.0{run62+=1;}else{run62=0;}if run62>=10&&post62.is_none(){post62=Some(t-switch.unwrap());}
if warm=="fixed"&&t==100 || warm=="sustained"&&sustained65==Some(t){w.config.policy.enabled=true;}
if let Some(f)=trace.as_mut(){let age_str=ages.iter().enumerate().filter(|(_,n)|**n>0).map(|(a,n)|format!("{a}:{n}")).collect::<Vec<_>>().join(";");let (cols,cell)=population(w.config.per_cohort);let ax=cols*cell+GAP;let hz=(62..=70).map(|age|{let i=w.inspect(ax as u32,((age-20)*ROW)as u32).unwrap();format!("{age}:{}:{}",i.retirements.unwrap(),i.exposed.unwrap())}).collect::<Vec<_>>().join(";");writeln!(f,"{t},{},{},{},{},{},{ni},{age_str},{hz}",s.retired,s.modal_age,s.mean_age,s.eligibility,ages.iter().sum::<u32>()).unwrap();}
if batch=="cohort-source"&&first[0].is_some(){break;}if switch.is_some_and(|at|t>=at+100){break;}if warm!="none"&&switch.is_none()&&t>=1000{break;}}
let s=w.stats.history().last().unwrap();writeln!(sum,"{name},{seed},{},{},{previous_tick_mode_at_switch},{},{},{},{},{},{},{},{},{},{},{},{},{},{imit}",w.tick(),val(switch),val(first[0]),val(first[1]),val(first[2]),dips[0],dips[1],dips[2],val(sustained65),val(post62),w.transition_new().map(|n|n.to_string()).unwrap_or_default(),if s.transition_a.is_finite(){s.transition_a.to_string()}else{String::new()},if s.transition_b.is_finite(){s.transition_b.to_string()}else{String::new()},s.retired,s.modal_age).unwrap();sum.flush().unwrap();}eprintln!("{name} complete elapsed {:.2}s",start.elapsed().as_secs_f64());}}

#[cfg(test)] mod tests {use super::*;
#[test] fn rational_retirement_age_matches_surviving_eligibles(){let mut c=RetirementConfig::default();c.per_cohort=2;c.rational=1.;c.random=0.;let mut w=RetirementWorld::new(c,1001).unwrap();w.step();assert!(w.agents().iter().enumerate().all(|(i,a)|a.retired==(w.age(i)>=65)));}
#[test] fn mortality_is_not_a_new_retirement(){let mut c=RetirementConfig::default();c.per_cohort=2;c.rational=1.;c.random=0.;let mut w=RetirementWorld::new(c,1001).unwrap();let old:Vec<_>=w.agents().iter().map(|a|a.born).collect();w.step();assert!(w.agents().iter().enumerate().filter(|(i,a)|a.born!=old[*i]).all(|(_,a)|!a.retired&&a.retired_at.is_none()));}
#[test] fn all_counted_does_not_forbid_imitator_retirement(){let mut c=RetirementConfig::default();c.per_cohort=2;c.counts=Counts::All;c.rational=0.8;c.random=0.;let mut w=RetirementWorld::new(c,1001).unwrap();w.run(10);assert!(w.agents().iter().any(|a|a.kind==Kind::Imitator&&a.retired));}
}
